FROM python:3.10-slim

RUN apt-get update && apt-get install -y git rsync \
    && git clone --branch v2.2.1 https://github.com/microsoft/graphrag.git /graphrag \
    && pip install --no-cache-dir /graphrag \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /graphrag

RUN graphrag init --root /graphrag_config --force

COPY ./.env /graphrag_config/.env
COPY ./settings.yaml /graphrag_config/settings.yaml

ENTRYPOINT ["graphrag"]