FROM apache/airflow:2.8.4-python3.10

# Argumento para definir o usuário Airflow (use seu UID local)
ARG AIRFLOW_UID=50000
ARG AIRFLOW_GID=0

# Define variáveis de ambiente do Airflow
ENV AIRFLOW_HOME=/opt/airflow
ENV PYTHONPATH="${AIRFLOW_HOME}/.local/lib/python3.9/site-packages:${PYTHONPATH}"
ENV PATH="${AIRFLOW_HOME}/.local/bin:${PATH}"

COPY --chown=${AIRFLOW_UID}:${AIRFLOW_GID} ./airflow-pipeline/requirements.txt /requirements.txt

# Mude para o usuário airflow ANTES de instalar com --user
USER $AIRFLOW_UID

RUN python -m pip install --no-cache-dir --user -r /requirements.txt

# Mudar temporariamente para root para criar/ajustar diretórios base
USER root
RUN mkdir -p ${AIRFLOW_HOME}/dags ${AIRFLOW_HOME}/logs ${AIRFLOW_HOME}/plugins ${AIRFLOW_HOME}/scripts ${AIRFLOW_HOME}/data \
    && chown -R ${AIRFLOW_UID}:${AIRFLOW_GID} ${AIRFLOW_HOME}

COPY --chown=${AIRFLOW_UID}:${AIRFLOW_GID} ./airflow-pipeline/dags/ /opt/airflow/dags/

# Switch back to the Airflow user for normal execution
USER ${AIRFLOW_UID}

WORKDIR ${AIRFLOW_HOME}