FROM python:3.10-slim

WORKDIR /service

COPY ./app/requirements.txt /service/requirements.txt
RUN pip install --no-cache-dir -r /service/requirements.txt

COPY ./app /service/app

COPY ./alembic.ini /service/alembic.ini

EXPOSE 8000

CMD ["bash", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
